{% set name = "tsml" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tsml-{{ version }}.tar.gz
  sha256: 8e75b131793d66939c8a84e2edf90329745b51ac16fa11350d96e401c756c2a4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - setuptools >=61
    - wheel
    - toml
    - python-build
    - pip
  run:
    - python >=3.8,<3.12
    - numba >=0.55.0,<0.58.0
    - numpy >=1.21.0,<1.25.0
    - pandas >=1.5.3,<2.1.0
    - scikit-learn >=1.0.0,<1.3.0
    - packaging >=20.0,<24.0

test:
  imports:
    - tsml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/time-series-machine-learning/tsml/
  dev_url: https://github.com/time-series-machine-learning/
  summary: A toolkit for time series machine learning algorithms.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MatthewMiddlehurst
