{% set name = "tsml" %}
{% set version = "0.5.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tsml-{{ version }}.tar.gz
  sha256: b2425f7efabfabeb7b282912c0b20ca0e5d037116500693576ef0b0ef409ff37

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - wheel
    - toml
    - python-build
    - pip
  run:
    - python >={{ python_min }}
    - numba >=0.55.0,<0.61.0
    - numpy >=1.21.0,<2.2.0
    - pandas >=1.5.3,<2.3.0
    - scikit-learn >=1.0.0,<1.4.0
    - packaging >=20.0

test:
  imports:
    - tsml
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/time-series-machine-learning/tsml/
  dev_url: https://github.com/time-series-machine-learning/
  summary: A development sandbox for time series machine learning algorithms.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MatthewMiddlehurst
