{% set name = "tsml" %}
{% set version = "0.6.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tsml-{{ version }}.tar.gz
  sha256: 4a966e663c1da09a03ea70b48969041172b2e7264a4a57a20d7b66d5a8ebefc4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - wheel
    - toml
    - python-build
    - pip
  run:
    - python >={{ python_min }}
    - numba >=0.55.0
    - numpy >=1.21.0
    - scipy >=1.9.0
    - pandas >=1.5.3
    - scikit-learn >=1.0.0
    - packaging >=20.0

test:
  imports:
    - tsml
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/time-series-machine-learning/tsml/
  dev_url: https://github.com/time-series-machine-learning/
  summary: A development sandbox for time series machine learning algorithms.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MatthewMiddlehurst
