{% set name = "tsml" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tsml-{{ version }}.tar.gz
  sha256: b2425f7efabfabeb7b282912c0b20ca0e5d037116500693576ef0b0ef409ff37

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.13
    - setuptools >=61
    - wheel
    - toml
    - python-build
    - pip
  run:
    - python >=3.8,<3.13
    - numba >=0.55.0
    - numpy >=1.21.0
    - pandas >=1.5.3
    - scikit-learn >=1.0.0
    - packaging >=20.0

test:
  imports:
    - tsml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/time-series-machine-learning/tsml/
  dev_url: https://github.com/time-series-machine-learning/
  summary: A toolkit for time series machine learning algorithms.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MatthewMiddlehurst
